// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/litixsoft/lx-golib/db (interfaces: IBaseDb)

// Package lxGoLibMocks is a generated GoMock package.
package lxGoLibMocks

import (
	gomock "github.com/golang/mock/gomock"
	db "github.com/litixsoft/lx-golib/db"
	reflect "reflect"
)

// MockIBaseDb is a mock of IBaseDb interface
type MockIBaseDb struct {
	ctrl     *gomock.Controller
	recorder *MockIBaseDbMockRecorder
}

// MockIBaseDbMockRecorder is the mock recorder for MockIBaseDb
type MockIBaseDbMockRecorder struct {
	mock *MockIBaseDb
}

// NewMockIBaseDb creates a new mock instance
func NewMockIBaseDb(ctrl *gomock.Controller) *MockIBaseDb {
	mock := &MockIBaseDb{ctrl: ctrl}
	mock.recorder = &MockIBaseDbMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIBaseDb) EXPECT() *MockIBaseDbMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockIBaseDb) Create(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockIBaseDbMockRecorder) Create(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIBaseDb)(nil).Create), arg0)
}

// Delete mocks base method
func (m *MockIBaseDb) Delete(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockIBaseDbMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIBaseDb)(nil).Delete), arg0)
}

// DeleteAll mocks base method
func (m *MockIBaseDb) DeleteAll(arg0 interface{}) (db.ChangeInfo, error) {
	ret := m.ctrl.Call(m, "DeleteAll", arg0)
	ret0, _ := ret[0].(db.ChangeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAll indicates an expected call of DeleteAll
func (mr *MockIBaseDbMockRecorder) DeleteAll(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockIBaseDb)(nil).DeleteAll), arg0)
}

// GetAll mocks base method
func (m *MockIBaseDb) GetAll(arg0, arg1 interface{}, arg2 *db.Options) (int, error) {
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockIBaseDbMockRecorder) GetAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIBaseDb)(nil).GetAll), arg0, arg1, arg2)
}

// GetCount mocks base method
func (m *MockIBaseDb) GetCount(arg0 interface{}) (int, error) {
	ret := m.ctrl.Call(m, "GetCount", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCount indicates an expected call of GetCount
func (mr *MockIBaseDbMockRecorder) GetCount(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCount", reflect.TypeOf((*MockIBaseDb)(nil).GetCount), arg0)
}

// GetOne mocks base method
func (m *MockIBaseDb) GetOne(arg0, arg1 interface{}) error {
	ret := m.ctrl.Call(m, "GetOne", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetOne indicates an expected call of GetOne
func (mr *MockIBaseDbMockRecorder) GetOne(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOne", reflect.TypeOf((*MockIBaseDb)(nil).GetOne), arg0, arg1)
}

// Setup mocks base method
func (m *MockIBaseDb) Setup(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "Setup", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Setup indicates an expected call of Setup
func (mr *MockIBaseDbMockRecorder) Setup(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Setup", reflect.TypeOf((*MockIBaseDb)(nil).Setup), arg0)
}

// Update mocks base method
func (m *MockIBaseDb) Update(arg0, arg1 interface{}) error {
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockIBaseDbMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIBaseDb)(nil).Update), arg0, arg1)
}

// UpdateAll mocks base method
func (m *MockIBaseDb) UpdateAll(arg0, arg1 interface{}) (db.ChangeInfo, error) {
	ret := m.ctrl.Call(m, "UpdateAll", arg0, arg1)
	ret0, _ := ret[0].(db.ChangeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAll indicates an expected call of UpdateAll
func (mr *MockIBaseDbMockRecorder) UpdateAll(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAll", reflect.TypeOf((*MockIBaseDb)(nil).UpdateAll), arg0, arg1)
}
