sudo: required

services:
  - docker
  
-language: go

before_install:
- docker pull golang:alpine

script:
  - go env
  - go version
  - ls -la
  - docker-compose build
  - docker-compose run lx_golib
  - docker-compose down
