sudo: required

services:
  - docker

-language: go

before_install:
- docker pull golang:alpine
- docker pull mongo:latest

script:
  - docker-compose build
  - docker-compose run lx_golib
  - docker-compose down
  - docker image prune -f
