sudo: required

services:
  - docker

-language: go

before_install:
- docker pull golang:alpine
- docker pull mongo:latest

script:
  - docker-compose -f ./build/single_latest.yml run lx_golib
  - docker-compose -f ./build/single_latest.yml down
  - docker image prune -f
